In [1]:
l = [110,200,300,400]

In [2]:
l

[110, 200, 300, 400]

In [3]:
import numpy as np

In [4]:
a = np.array(l)

In [5]:
a

array([110, 200, 300, 400])

In [7]:
b = np.array([100,2000,True,"hello"])

In [8]:
b

array(['100', '2000', 'True', 'hello'], dtype='<U11')

In [12]:
c = np.array([100,100.7,True,200])

In [13]:
c

array([100. , 100.7,   1. , 200. ])

In [11]:
#very powerful methods supported by array

In [10]:
a.mean()

252.5

In [14]:
#slicing arrays

In [15]:
a

array([110, 200, 300, 400])

In [22]:
d = a[2:4]

In [23]:
d

array([300, 400])

In [24]:
d[:] = 111

In [25]:
d

array([111, 111])

In [26]:
a

array([110, 200, 111, 111])