In [1]:
import numpy as np

In [4]:
mydata = np.arange(0,20)
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [17]:
np.reshape(mydata,(5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [20]:
matr1 = np.reshape(mydata, (5,4), order="c") 
matr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
matr1[2,2]

10

In [23]:
matr2 = np.reshape(mydata, (5,4), order="f")
matr2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [25]:
matr2[0,2]

10

---

---

In [26]:
r1 = ['I','am','happy']
r2 = ['What','a','day']
r3 =[1,2,3]

In [27]:
[r1,r2,r3]

[['I', 'am', 'happy'], ['What', 'a', 'day'], [1, 2, 3]]

In [30]:
np.array([r1,r2,r3])

array([['I', 'am', 'happy'],
       ['What', 'a', 'day'],
       ['1', '2', '3']], dtype='<U5')